spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: jwt-server
              uri: lb://JWT-SERVER
              predicates:
                - Path=/auth/**

            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**

  application:
    name: GATEWAY-SERVICE

eureka:
   client:
     service-url:
       defaultZone: http://localhost:8761/eureka

server:
  port: 9013
